name: ngam_plan
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  elegant_nav_bar: ^0.0.22
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.12.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^8.2.0
  lucide_icons_flutter: ^3.1.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
